#!/bin/bash
# Script created by Rainer Rössler (rainer-at-linuxmuster.net)
# modified by Frank Schütte fschuett@gymnasium-himmelsthuer.de
# License: Free Software (License GPLv3)
# 20.7.2014
. /usr/share/linuxmuster-client/config || exit 1
. ${USERCONFIG} || exit 1
. ${HELPERFUNCTIONS} || exit 1

[ $VOLUME == shares ] ||  return 0

[ ${HOMEDIR%/*/*} != '/home/workstations' ] && return 0

$LOGGING && log_msg post-mount "Entering 009-no-share-exam $1 $2"

umount /home/share

# Das Script wird nicht mit einem "exit 0" beendet, da sonst
# das Hauptscript /usr/sbin/linuxmuster-pam-mount, aus dem heraus
# es aufgerufen wird, damit beendet würde.
